#!/usr/bin/env python3
import sys, os
if sys.platform == 'darwin':
    sys.path.insert(0,os.path.normpath(os.path.join(os.path.abspath(__file__),'..')))

from argparse import ArgumentParser
from core_pe.app import DupeGuru
from cli.inter import DupeGuruView

def main():

    parser = ArgumentParser()
    parser.add_argument("-v", "--verbosity", action="count",
                    help="increase output verbosity")
    args = parser.parse_args()
    print(args)

    model = DupeGuru(DupeGuruView())
    print(model)

if __name__ == '__main__':
    main()
